### PR TITLE
Sync with upstream 2.0.4

### PR DESCRIPTION
**Pull request by Daft-Freak**
Emscripten changes:
- Gamepad/joystick cleanups
- Normalised touch coords

all sdl2 related tests still pass

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

**Comment by kripken** [comment]
Does this need further testing, or can we add a `version_10` tag and update emscripten to use version 10?

**Comment by Daft-Freak** [comment]
I've done some more testing of touch/gamepad and everything seems fine.

**Comment by kripken** [comment]
Ok, thanks, I'll add `version_10`.

**Pull request merged**
