### PR TITLE
Implement workaround for audio in chrome

### LINKED ISSUE #57: No sound in chrome - due to Autoplay policy changes
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes are live, and this causes audioContext to be muted if it isn't created after user interaction. 
I've added quick work-around to my code:

document.addEventListener("click", function(){
    try {
        if (!SDL2 || !SDL2.audioContext || !SDL2.audioContext.resume) return;
            SDL2.audioContext.resume();
        } catch (err) {}
});

Maybe something like this (+keyboard events) should be added to SDL port?

### PR DESCRIPTION
**Pull request by Daft-Freak**
Should fix #57 (and probably #19 since Safari uses the same method now). (As usual, PR is mainly because I'd like someone to test it.)

### CODE REVIEW

**Comment by kevzettler** [comment]
whats needed to get this merged?

**Comment by Daft-Freak** [comment]
I might have been waiting to see if anyone had comments... I think there was a discussion about how Emscripten should handle this in general.

**Comment by kripken** [comment]
I think some general discussion led to https://github.com/emscripten-core/emscripten/pull/10843 but thta will just fix SDL1 and OpenAL. So this looks good as a fix for SDL2.

**Comment by kevzettler** [comment]
So it sounds like this is ready for merge?

**Comment by Daft-Freak** [comment]
Just needed to find something to test it on to make sure it actually worked...

**Pull request merged**
