### PR TITLE
Fix alt key being a nav key

### PR DESCRIPTION
**Pull request by feliwir**
Fixes issue mentioned in #132 
See @Daft-Freak

### CODE REVIEW

**Comment by feliwir** [comment]
Can this please get merged anytime soon? @kripken

**Comment by kripken** [comment]
@Daft-Freak is the best person to review this - I don't know the code that much.

If @Daft-Freak is not available, we can probably figure this out together, though, with some new tests and such.

**Comment by Daft-Freak** [comment]
I _think_ this should be okay. It's reverting a part of 993758c3cde567d121fee9cf4ad095fe009240ea, but Alt+[key] wasn't a part of the issue that was fixing and I was wrong about it not generating any `keypress` events. I only have the usual nitpick-y comment of "prefix the commit message with emscripten:".

(I've got another key event patch I still haven't got around to testing 65c131602a0039437bb1a8782249828c4eba9fd4)

**Comment by feliwir** [comment]
@Daft-Freak i changed the commit message accordingly

**Comment by Daft-Freak** [comment]
Okay, merging and hoping it doesn't break some other usecase I'm unaware of. (Turns out this is hard to get right!)

Anyway, thanks!

**Pull request merged**
