### PR TITLE
Fixed opening brace issue when SDL_PROTOTYPES_ONLY is defined

### PR DESCRIPTION
**Pull request by gabrielcuvillier**
Hello,
When SDL_PROTOTYPES_ONLY is being defined, there is a compilation error because of a missing opening brace in SDL_SysWM.h

The missing code is
```
#ifdef __cplusplus
extern "C" {
#endif
```
... in the #ifdef SDL_PROTOTYPES_ONLY block

(this code is already done in the #else block. The corresponding closing brace is always done at the end of the file, regardless of the definition of SDL_PROTOTYPES_ONLY)

This PR solves the issue

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Looks like common code, might want to try the [upstream bug tracker](https://bugzilla.libsdl.org/).

**Comment by gabrielcuvillier** [comment]
Hum, according to the bugtracker, this issue have been already fixed in SDL v2.0.9
https://bugzilla.libsdl.org/show_bug.cgi?id=4362

Maybe there some synchronization to do with upstream SDL ?

**Comment by Daft-Freak** [comment]
We should be up-to-date with 2.0.9. Looks like that commit happened a bit later (cc035dcc4faaec9c2122c241f83ad6b5296e42b1).

**Comment by gabrielcuvillier** [comment]
Ok, so what is the best thing we can do to fix the regression ? Is this on upstream SDL side ?

**Comment by Daft-Freak** [comment]
I've cherry-picked the upstream fix.

**Comment by gabrielcuvillier** [comment]
Ok good, so I guess we can close the issue. Thx!

**Pull request closed without merging**
