### PR TITLE
[WIP] SDL2 PROXY_TO_PTHREAD Fixes

### PR DESCRIPTION
**Pull request by jakogut**
This pull request fixes undefined references and proxying issues when using SDL2 with `PROXY_TO_PTHREAD=1`.

Requires https://github.com/emscripten-core/emscripten/pull/8254

This was tested with `tests/sdl2_gl_frames_swap.c` and `PROXY_TO_PTHREAD=1`.

This still requires creating a WebGL context and making it current as documented here:
https://github.com/emscripten-core/emscripten/issues/7684#issuecomment-448446674

Fixes: https://github.com/emscripten-core/emscripten/issues/6009

### CODE REVIEW

**Comment by jakogut** [comment]
@juj I'm open to feedback about a better way to do this.

**Comment by conversy** [comment]
I understood that this PR would enable the use of SDL with threads, is this correct? If so, I'm very interested into it. I'm not sure I have the skills to test it though.

**Comment by jakogut** [comment]
@conversy It enables SDL2 applications to be run with the option `PROXY_TO_PTHREAD=1`, which runs the `main` function in a separate thread.

**Comment by jakogut** [comment]
@conversy I don't know if this is what you're actually wanting, but I'm now working on SDL2 threads support through an unrelated turn of events. I've made an issue here: https://github.com/emscripten-core/emscripten/issues/8300

**Comment by conversy** [comment]
My application says: "screen is not defined" when run in a browser. I understood that it was because I also use threads with SDL. Is this PR supposed to fix it?
I gave it a try (em 1.38.29, cloning SDL port, applying the PR, compiling with EMCC_LOCAL_PORTS) to no avail...

**Comment by kripken** [comment]
Curious to hear @Daft-Freak's thoughts here. My general feeling is that we can fix this another way, by replacing say `Emscripten_SetWindowTitle` with a new emscripten C API function `emscripten_set_window_title`, and we'd handle proxying of that in emscripten itself. That would be less work here, more work shared in emscripten, unless I'm missing something?

**Comment by Daft-Freak** [comment]
A lot of this could be done with new emscripten API. `emscripten_set_window_title` and `emscripten_get_screen_size` would likely be useful API additions anyway, maybe something like `emscripten_set_element_style(selector, property, value)` could be added for setting the cursor.

That would leave the framebuffer and creating cursors, which uses a canvas to convert some pixel data into a data-url, maybe there's some way we could do this that would also work on a worker?

**Comment by Daft-Freak** [comment]
Small comment on the PR itself: we usually just prefix commits with `emscripten:`

**Comment by fallenoak** [comment]
I just gave this PR a spin and it works well for my use case. What are the next steps? Implementing functions like `emscripten_set_window_title` in the main emscripten code base and updating this PR to make use of them?

**Comment by kripken** [comment]
@fallenoak yes, exactly, that's the right order. I don't think anyone's working on that yet, so if you or anyone else wants to, that would be great!

**Pull request closed without merging**
